containers:
  - name: wallabag
    image: docker.io/wallabag/wallabag:latest
    ports:
      - local: 8080
        target: 80
    env:
      - name: SYMFONY__ENV__DOMAIN_NAME
        value: "http://{{ inventory_hostname }}:8080"
    volumes:
      - src: /srv/wallabag/data
        dest: /var/www/wallabag/data
      - src: /srv/wallabag/images
        dest: /var/www/wallabag/web/assets/images
